In [1]:
import pandas as pd
df = pd.read_csv('train_critic.csv')
import nltk
from nltk import word_tokenize

# Match Nouns and Adjectives in question and responses

In [2]:
def get_match(row):
    question = str(row['questions'])
    answer = str(row['answers'])
    knowledge = str(row['knowledge'])
    question_tokens = word_tokenize(question)
    question_tags = nltk.pos_tag(question_tokens, tagset="universal")
    answer_tokens = word_tokenize(answer)
    answer_tags = nltk.pos_tag(answer_tokens, tagset="universal")
    knowledge_tokens = word_tokenize(knowledge)
    knowledge_tags = nltk.pos_tag(knowledge_tokens, tagset="universal")
    question_nouns, question_adjs, answer_nouns, answer_adjs, knowledge_nouns, knowledge_adjs = set(), set(), set(), set(), set(), set()
    for tag in question_tags:
        if tag[1]=='NOUN':
            question_nouns.add(tag[0])
        elif tag[1]=='ADJ':
            question_adjs.add(tag[0])
    for tag in answer_tags:
        if tag[1]=='NOUN':
            answer_nouns.add(tag[0])
        elif tag[1]=='ADJ':
            answer_adjs.add(tag[0])
    for tag in knowledge_tags:
        if tag[1]=='NOUN':
            knowledge_nouns.add(tag[0])
        elif tag[1]=='ADJ':
            knowledge_adjs.add(tag[0])

    if len(answer_nouns)==0 and len(question_nouns)==0:
        row['question_noun_match']=0
    elif len(answer_nouns)==0:
        row['question_noun_match']=1
    else:
        row['question_noun_match'] = len(answer_nouns-question_nouns)/len(answer_nouns)

    if len(answer_nouns)==0 and len(knowledge_nouns)==0:
        row['knowledge_noun_match']=0
    elif len(answer_nouns)==0:
        row['knowledge_noun_match']=1
    else:
        row['knowledge_noun_match'] = len(answer_nouns-knowledge_nouns)/len(answer_nouns)

    if len(answer_adjs)==0 and len(question_adjs)==0:
        row['question_adj_match']=0
    elif len(answer_adjs)==0:
        row['question_adj_match']=1
    else:
        row['question_adj_match'] = len(answer_adjs-question_adjs)/len(answer_adjs)

    if len(answer_adjs)==0 and len(knowledge_adjs)==0:
        row['knowledge_adj_match']=0
    elif len(answer_adjs)==0:
        row['knowledge_adj_match']=1
    else:
        row['knowledge_adj_match'] = len(answer_adjs-knowledge_adjs)/len(answer_adjs)
    return row


In [3]:
df = df.apply(lambda row: get_match(row), axis=1)
df.question_adj_match

0        0.666667
1        1.000000
2        1.000000
3        1.000000
4        1.000000
           ...   
18352    1.000000
18353    1.000000
18354    1.000000
18355    1.000000
18356    1.000000
Name: question_adj_match, Length: 18357, dtype: float64

In [4]:
df.question_adj_match.value_counts()

question_adj_match
1.000000    15299
0.000000     1149
0.500000      761
0.666667      570
0.750000      297
0.800000      121
0.333333       68
0.833333       35
0.600000       22
0.857143       18
0.250000        9
0.714286        3
0.888889        2
0.875000        2
0.400000        1
Name: count, dtype: int64

In [5]:
df.question_noun_match.value_counts()

question_noun_match
1.000000    9473
0.750000    1400
0.666667    1373
0.500000    1167
0.800000     995
0.833333     737
0.600000     466
0.857143     429
0.333333     334
0.714286     306
0.875000     301
0.000000     295
0.888889     162
0.400000     135
0.571429     103
0.777778     102
0.250000      94
0.625000      73
0.900000      72
0.909091      48
0.700000      35
0.428571      28
0.818182      27
0.916667      23
0.555556      20
0.200000      19
0.727273      17
0.923077      15
0.846154      13
0.928571      12
0.444444      11
0.769231      10
0.636364       6
0.285714       6
0.375000       5
0.785714       5
0.692308       5
0.866667       4
0.933333       4
0.142857       4
0.937500       4
0.166667       3
0.733333       2
0.545455       2
0.583333       2
0.941176       1
0.764706       1
0.850000       1
0.944444       1
0.789474       1
0.125000       1
0.300000       1
0.230769       1
0.956522       1
0.538462       1
Name: count, dtype: int64

In [6]:
df.knowledge_noun_match.value_counts()

knowledge_noun_match
1.000000    4410
0.000000    2359
0.500000    2318
0.333333    1427
0.666667    1208
            ... 
0.105263       1
0.866667       1
0.950000       1
0.157895       1
0.916667       1
Name: count, Length: 80, dtype: int64

In [7]:
df.knowledge_adj_match.value_counts()

knowledge_adj_match
1.000000    10234
0.000000     3885
0.500000     1918
0.666667      887
0.333333      577
0.750000      312
0.250000      159
0.800000      106
0.600000       89
0.400000       59
0.200000       45
0.833333       33
0.714286       12
0.571429       10
0.428571        6
0.857143        6
0.166667        4
0.875000        3
0.285714        3
0.142857        3
0.222222        1
0.636364        1
0.125000        1
0.625000        1
0.444444        1
0.777778        1
Name: count, dtype: int64

In [8]:
df.to_csv('train_critic_match.csv', index=False)

In [9]:
df = pd.read_csv('train_critic_match.csv')
df

questions   
0      Can you imagine the world without internet acc...  \
1      Can you imagine the world without internet acc...   
2      Can you imagine the world without internet acc...   
3      Can you imagine the world without internet acc...   
4      I am just finishing my university course and I...   
...                                                  ...   
18352                        I live on a farm with pigs!   
18353  I live on a farm with pigs! : Neat! So you rai...   
18354  I live on a farm with pigs! : Neat! So you rai...   
18355  I live on a farm with pigs! : Neat! So you rai...   
18356  I live on a farm with pigs! : Neat! So you rai...   

                                                 answers   
0      No I could not! I couldn't imagine living when...  \
1      It used to be restricted, but around 1995, the...   
2      Yes, it was developed from a government funded...   
3      What is your favorite thing to do with interne...   
4      Yes, I perform administrative duties as a phar...   
...                                                  ...   
18352  That's pretty neat. Pig farming is raising and...   
18353  Sounds like a great cycle. Pigs are farmed mos...   
18354  Historically farm pigs were kept in small numb...   
18355  Another use for pigs is to dispose of municipa...   
18356  Creepy indeed. In developed nations commercial...   

                                               knowledge  hallucination   
0      Internet access was once rare, but has grown r...              1  \
1      Use by a wider audience only came in 1995 when...              1   
2      The Internet developed from the ARPANET, which...              1   
3      Internet access is the ability of individuals ...              1   
4      They may also perform administrative duties in...              1   
...                                                  ...            ...   
18352  Pig farming is the raising and breeding of dom...              1   
18353      Pigs are farmed principally to be eaten (e.g.              1   
18354  Historically, farm pigs were kept in small num...              1   
18355  Pigs have been farmed to dispose of municipal ...              1   
18356  In developed nations, commercial farms house t...              1   

       entailment  generic  uncooperative  question_noun_match   
0               0        0              0             0.500000  \
1               1        0              0             1.000000   
2               1        0              0             0.857143   
3               1        0              0             0.500000   
4               1        0              0             1.000000   
...           ...      ...            ...                  ...   
18352           1        0              0             0.833333   
18353           1        0              0             1.000000   
18354           1        0              0             0.666667   
18355           1        0              0             0.750000   
18356           1        0              0             0.750000   

       knowledge_noun_match  question_adj_match  knowledge_adj_match  
0                  0.500000            0.666667             0.666667  
1                  0.000000            1.000000             0.000000  
2                  0.285714            1.000000             1.000000  
3                  0.625000            1.000000             1.000000  
4                  0.666667            1.000000             0.000000  
...                     ...                 ...                  ...  
18352              0.333333            1.000000             1.000000  
18353              0.800000            1.000000             1.000000  
18354              0.166667            1.000000             0.000000  
18355              0.500000            1.000000             0.000000  
18356              0.250000            1.000000             0.333333  

[18357 rows x 11 columns]

####  Dataset for VRM

In [ ]:
import json
responses, vrm = [], []
with open('train.json') as data:
    data = json.load(data)
for d in data:
   utterances = d['utterances']
   for utterance in utterances:
      response = utterance['original_response']
      responses.append(response)
      vrm.append(utterance['VRM'])
    
data = pd.DataFrame({'responses': responses, 'VRM': vrm})
data

responses  \
0      No I could not! I couldn't imagine living when...   
1      It used to be restricted, but around 1995, the...   
2      Yes, it was developed from a government funded...   
3      What is your favorite thing to do with interne...   
4      Yes, I perform administrative duties as a phar...   
...                                                  ...   
18352  That's pretty neat. Pig farming is raising and...   
18353  Sounds like a great cycle. Pigs are farmed mos...   
18354  Historically farm pigs were kept in small numb...   
18355  Another use for pigs is to dispose of municipa...   
18356  Creepy indeed. In developed nations commercial...   

                          VRM  
0          [Disclosure, Ack.]  
1               [Edification]  
2          [Disclosure, Ack.]  
3      [Disclosure, Question]  
4          [Disclosure, Ack.]  
...                       ...  
18352      [Disclosure, Ack.]  
18353            [Disclosure]  
18354            [Disclosure]  
18355            [Disclosure]  
18356      [Disclosure, Ack.]  

[18357 rows x 2 columns]

In [ ]:
data.to_csv('train_vrm.csv', index=False)

In [11]:
from nltk.tokenize import word_tokenize
import json
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
import numpy as np
import pandas as pd

In [12]:
data = pd.read_csv('train_vrm.csv')
data.dropna(inplace=True)
cctext = np.array(data['responses'])
ccinp = []
li = []
stop_words = set(stopwords.words('english'))  
stop_words = list(stop_words) + [',', '(', ')', '“', '”', '.', '-', ':', '’', '~', '!', '`', '@', '#', '$', '%', '&', '*','+', '/', ';', '<', '>', '?', '[', ']', '{', '}', '_', 'I', 'Im', 'Ive', 'Its', 'im', 'IM']
for i in cctext:
  word_tokens = word_tokenize(i)
  word_tokens = [w.lower() for w in word_tokens] 
  filtered_sentence = [w for w in word_tokens if not w.lower() in stop_words]
  ccinp.append(' '.join(filtered_sentence))
data.VRM.isna().sum()


0

In [ ]:
import gensim
import gensim.downloader as gensim_api

#### Creation of dataset using Word2Vec

In [ ]:
from tqdm import tqdm
import numpy as np
from sklearn.preprocessing import StandardScaler
import pandas as pd
nlp = gensim.models.word2vec.Word2Vec(ccinp, vector_size=200, window=8, min_count=1, sg=1)
w2v_words_cc=list(nlp.wv.index_to_key)
listof_sent_vec_cc=[]
#tqdm is for improving speed and making progressbar
for sent in tqdm(ccinp): 
    sent_vec = np.zeros(200) 
    cnt_words =0; 
    for word in sent: 
        if word in w2v_words_cc:
            vec = nlp.wv[word]
            sent_vec += vec
            cnt_words += 1
    if cnt_words != 0:
        sent_vec /= cnt_words
    listof_sent_vec_cc.append(sent_vec)
# Label = [0 for i in range]
list_col=tuple(range(200))
Scaler = StandardScaler()
train_vec = Scaler.fit_transform(listof_sent_vec_cc)
W2v_data=pd.DataFrame(data=train_vec, columns=list_col)
W2v_data
Label = data.VRM
W2v_data['Class'] = Label
W2v_data

100%|██████████| 15624/15624 [00:01<00:00, 12719.91it/s]


0         1         2         3         4         5         6  \
0      0.462443 -0.648214 -0.204216 -0.750656 -0.161676  0.441363  0.975576   
1     -0.892674  0.397247  1.712281 -0.266441  0.546694 -1.177927 -1.798441   
2     -2.024475  0.167198  0.210629  0.162576  0.171703 -0.497342 -0.736159   
3     -0.111489 -0.591906  0.654217 -0.737723 -0.427298 -0.874863 -0.801317   
4      0.633736  1.044750  0.613459 -0.842709 -1.041950  0.775464  0.768036   
...         ...       ...       ...       ...       ...       ...       ...   
15619  1.344859  0.945527 -0.178848 -1.213570 -0.283548  0.168942  0.706152   
15620  0.219868  0.290521  0.793351 -0.589632 -0.472196 -1.328954 -1.360351   
15621  1.020780  0.222036  0.176755 -0.625057 -0.457251 -0.973826 -0.636060   
15622  1.026205  0.219393 -0.498888  0.095780 -0.582338 -0.244453  0.288778   
15623  0.047618 -0.201987  0.017452  0.385239 -0.261925 -0.204268 -0.065310   

              7         8         9  ...       191       192       193  \
0     -0.129727  0.859047  0.010340  ... -0.047387  0.045734  0.758852   
1     -0.996260  0.472980  0.130272  ... -1.214490 -1.464557 -2.065165   
2      0.495584 -0.666258 -1.519241  ... -0.465195  0.303929  0.251058   
3     -0.706366  0.244655  0.385328  ... -0.082242  0.640483  0.497839   
4     -1.894932  0.167199  1.234591  ... -1.156955 -0.481076 -0.189782   
...         ...       ...       ...  ...       ...       ...       ...   
15619 -0.988840  0.883456 -0.504044  ...  0.710630  0.095534  1.291899   
15620 -0.396865  0.687022 -0.564925  ... -0.147550  0.321806  0.266557   
15621 -0.610962  0.393407  0.249726  ... -0.182051  0.201971  0.210465   
15622  0.181844 -0.002423 -0.447784  ...  0.708287  0.203562  0.661308   
15623 -0.080510 -0.290408  0.498712  ... -0.688945 -0.040412 -0.136533   

            194       195       196       197       198       199  \
0      0.014101 -0.286791 -0.949250  1.614293  0.587406  0.526198   
1     -0.145099 -1.352880  0.694834  0.571474 -1.166704 -2.419448   
2     -1.399697 -1.579557 -1.470001  0.180500 -0.207395 -0.043401   
3     -0.236869 -0.042228 -0.260964  0.296474  0.239225  0.320878   
4     -0.624061 -1.174468 -0.849011  0.787156 -0.034736  0.219846   
...         ...       ...       ...       ...       ...       ...   
15619  0.734682  0.332472 -0.612829  0.933633  1.181174  1.364087   
15620 -0.487287 -0.487561  0.494551  0.481173  0.297513 -0.163041   
15621 -0.160972 -0.306232  0.847575  0.126749  0.836687  0.656529   
15622  0.046254  0.723221  0.254110 -0.191085  1.127961  0.987329   
15623 -0.477569 -0.411462 -0.314406  0.346568 -0.347134 -0.395105   

                            Class  
0          ['Disclosure', 'Ack.']  
1                 ['Edification']  
2          ['Disclosure', 'Ack.']  
3      ['Disclosure', 'Question']  
4          ['Disclosure', 'Ack.']  
...                           ...  
15619      ['Disclosure', 'Ack.']  
15620     ['Ack.', 'Edification']  
15621     ['Ack.', 'Edification']  
15622                    ['Ack.']  
15623      ['Disclosure', 'Ack.']  

[15624 rows x 201 columns]

In [ ]:
classes = ['Disclosure', 'Edification', 'Question', 'Ack.', 'Advisement']
# classes = set()
# for classes in W2v_data.Class:
#     for itr in classes:
#         if itr in classes:
#             continue
#         classes.add(itr)
# classes
W2v_data.dropna(inplace=True)
def getClassAttributes(row, attr):
    label = row["Class"]
    # print(label)
    try:
        if attr in label:
            row[attr] = 1
        else:
            row[attr] = 0
        return row
    except:
        print(attr, label)

for itr in classes:
    print(itr)
    W2v_data = W2v_data.apply(lambda row: getClassAttributes(row, itr), axis=1)
W2v_data.isna().sum()


Disclosure
Edification
Question
Ack.
Advisement


0              0
1              0
2              0
3              0
4              0
              ..
Disclosure     0
Edification    0
Question       0
Ack.           0
Advisement     0
Length: 206, dtype: int64

#### Save dataset for VRM classification using word2vec vectors

In [ ]:
W2v_data.to_csv('train_vrm_vectors.csv')

In [ ]:
W2v_data

0         1         2         3         4         5         6  \
0      0.462443 -0.648214 -0.204216 -0.750656 -0.161676  0.441363  0.975576   
1     -0.892674  0.397247  1.712281 -0.266441  0.546694 -1.177927 -1.798441   
2     -2.024475  0.167198  0.210629  0.162576  0.171703 -0.497342 -0.736159   
3     -0.111489 -0.591906  0.654217 -0.737723 -0.427298 -0.874863 -0.801317   
4      0.633736  1.044750  0.613459 -0.842709 -1.041950  0.775464  0.768036   
...         ...       ...       ...       ...       ...       ...       ...   
15619  1.344859  0.945527 -0.178848 -1.213570 -0.283548  0.168942  0.706152   
15620  0.219868  0.290521  0.793351 -0.589632 -0.472196 -1.328954 -1.360351   
15621  1.020780  0.222036  0.176755 -0.625057 -0.457251 -0.973826 -0.636060   
15622  1.026205  0.219393 -0.498888  0.095780 -0.582338 -0.244453  0.288778   
15623  0.047618 -0.201987  0.017452  0.385239 -0.261925 -0.204268 -0.065310   

              7         8         9  ...       196       197       198  \
0     -0.129727  0.859047  0.010340  ... -0.949250  1.614293  0.587406   
1     -0.996260  0.472980  0.130272  ...  0.694834  0.571474 -1.166704   
2      0.495584 -0.666258 -1.519241  ... -1.470001  0.180500 -0.207395   
3     -0.706366  0.244655  0.385328  ... -0.260964  0.296474  0.239225   
4     -1.894932  0.167199  1.234591  ... -0.849011  0.787156 -0.034736   
...         ...       ...       ...  ...       ...       ...       ...   
15619 -0.988840  0.883456 -0.504044  ... -0.612829  0.933633  1.181174   
15620 -0.396865  0.687022 -0.564925  ...  0.494551  0.481173  0.297513   
15621 -0.610962  0.393407  0.249726  ...  0.847575  0.126749  0.836687   
15622  0.181844 -0.002423 -0.447784  ...  0.254110 -0.191085  1.127961   
15623 -0.080510 -0.290408  0.498712  ... -0.314406  0.346568 -0.347134   

            199                       Class  Disclosure  Edification  \
0      0.526198      ['Disclosure', 'Ack.']           1            0   
1     -2.419448             ['Edification']           0            1   
2     -0.043401      ['Disclosure', 'Ack.']           1            0   
3      0.320878  ['Disclosure', 'Question']           1            0   
4      0.219846      ['Disclosure', 'Ack.']           1            0   
...         ...                         ...         ...          ...   
15619  1.364087      ['Disclosure', 'Ack.']           1            0   
15620 -0.163041     ['Ack.', 'Edification']           0            1   
15621  0.656529     ['Ack.', 'Edification']           0            1   
15622  0.987329                    ['Ack.']           0            0   
15623 -0.395105      ['Disclosure', 'Ack.']           1            0   

       Question  Ack.  Advisement  
0             0     1           0  
1             0     0           0  
2             0     1           0  
3             1     0           0  
4             0     1           0  
...         ...   ...         ...  
15619         0     1           0  
15620         0     1           0  
15621         0     1           0  
15622         0     1           0  
15623         0     1           0  

[13217 rows x 206 columns]

In [13]:
data = pd.read_csv('train_critic_match.csv')
data.head()

questions   
0  Can you imagine the world without internet acc...  \
1  Can you imagine the world without internet acc...   
2  Can you imagine the world without internet acc...   
3  Can you imagine the world without internet acc...   
4  I am just finishing my university course and I...   

                                             answers   
0  No I could not! I couldn't imagine living when...  \
1  It used to be restricted, but around 1995, the...   
2  Yes, it was developed from a government funded...   
3  What is your favorite thing to do with interne...   
4  Yes, I perform administrative duties as a phar...   

                                           knowledge  hallucination   
0  Internet access was once rare, but has grown r...              1  \
1  Use by a wider audience only came in 1995 when...              1   
2  The Internet developed from the ARPANET, which...              1   
3  Internet access is the ability of individuals ...              1   
4  They may also perform administrative duties in...              1   

   entailment  generic  uncooperative  question_noun_match   
0           0        0              0             0.500000  \
1           1        0              0             1.000000   
2           1        0              0             0.857143   
3           1        0              0             0.500000   
4           1        0              0             1.000000   

   knowledge_noun_match  question_adj_match  knowledge_adj_match  
0              0.500000            0.666667             0.666667  
1              0.000000            1.000000             0.000000  
2              0.285714            1.000000             1.000000  
3              0.625000            1.000000             1.000000  
4              0.666667            1.000000             0.000000

# BEGIN Classification

##### Model for Hallucination

In [14]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
X = data[['question_noun_match', 'knowledge_noun_match', 'question_adj_match', 'knowledge_adj_match']]
y = data['hallucination']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)
dtc_hallucination = DecisionTreeClassifier()
dtc_hallucination.fit(X_train, y_train)

DecisionTreeClassifier()

In [15]:
y_pred = dtc_hallucination.predict(X_test)
from sklearn.metrics import accuracy_score, confusion_matrix, f1_score
accuracy_score(y_test, y_pred)

0.8352941176470589

In [16]:
confusion_matrix(y_test, y_pred)

array([[ 713,  488],
       [ 268, 3121]])

In [17]:
f1_score(y_test, y_pred)

0.8919691340382967

##### Model for Entailment

In [18]:
dtc_entailment = DecisionTreeClassifier()
dtc_entailment.fit(X_train, y_train)

DecisionTreeClassifier()

In [19]:
y_pred = dtc_entailment.predict(X_test)
from sklearn.metrics import accuracy_score, confusion_matrix
accuracy_score(y_test, y_pred)

0.8352941176470589

In [20]:
confusion_matrix(y_test, y_pred)

array([[ 713,  488],
       [ 268, 3121]])

In [21]:
f1_score(y_test, y_pred)

0.8919691340382967

##### Model for Generic

In [22]:
dtc_generic = DecisionTreeClassifier()
dtc_generic.fit(X_train, y_train)

DecisionTreeClassifier()

In [23]:
y_pred = dtc_generic.predict(X_test)
from sklearn.metrics import accuracy_score, confusion_matrix
accuracy_score(y_test, y_pred)

0.835511982570806

In [24]:
confusion_matrix(y_test, y_pred)

array([[ 713,  488],
       [ 267, 3122]])

In [25]:
f1_score(y_test, y_pred)

0.8921274467781112

##### Model for Uncooperative

In [26]:
dtc_uncooperative = DecisionTreeClassifier()
dtc_uncooperative.fit(X_train, y_train)

DecisionTreeClassifier()

In [27]:
y_pred = dtc_uncooperative.predict(X_test)
from sklearn.metrics import accuracy_score, confusion_matrix
accuracy_score(y_test, y_pred)

0.835511982570806

In [28]:
confusion_matrix(y_test, y_pred)

array([[ 712,  489],
       [ 266, 3123]])

In [29]:
f1_score(y_test, y_pred)

0.8921582631052706

# VRM Classification

##### Model for Disclosure

In [30]:
import pandas as pd
data = pd.read_csv('train_vrm_vectors.csv')
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
X = data.iloc[:,2:201]

In [31]:
y = data['Disclosure']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

dtc_disclocure = DecisionTreeClassifier()
dtc_disclocure.fit(X_train, y_train)

DecisionTreeClassifier()

In [32]:
y_pred = dtc_disclocure.predict(X_test)
from sklearn.metrics import accuracy_score, confusion_matrix, f1_score
accuracy_score(y_test, y_pred)

0.5434190620272314

In [33]:
confusion_matrix(y_test, y_pred)

array([[ 395,  736],
       [ 773, 1401]])

In [34]:
f1_score(y_test, y_pred)

0.6499652052887961

##### Model for Edification

In [35]:
y = data['Edification']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

dtc_edification = DecisionTreeClassifier()
dtc_edification.fit(X_train, y_train)

DecisionTreeClassifier()

In [36]:
y_pred = dtc_edification.predict(X_test)
from sklearn.metrics import accuracy_score, confusion_matrix
accuracy_score(y_test, y_pred)

0.5131618759455371

In [37]:
confusion_matrix(y_test, y_pred)

array([[889, 812],
       [797, 807]])

In [38]:
f1_score(y_test, y_pred)

0.5007756748371083

##### Model for Question

In [39]:
y = data['Question']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

dtc_question = DecisionTreeClassifier()
dtc_question.fit(X_train, y_train)

DecisionTreeClassifier()

In [40]:
y_pred = dtc_question.predict(X_test)
from sklearn.metrics import accuracy_score, confusion_matrix
accuracy_score(y_test, y_pred)

0.7878971255673223

In [41]:
f1_score(y_test, y_pred)

0.09548387096774194

In [42]:
confusion_matrix(y_test, y_pred)

array([[2567,  412],
       [ 289,   37]])

##### Model for Acknowledgement

In [43]:
y = data['Ack.']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

dtc_ack = DecisionTreeClassifier()
dtc_ack.fit(X_train, y_train)

DecisionTreeClassifier()

In [44]:
y_pred = dtc_disclocure.predict(X_test)
from sklearn.metrics import accuracy_score, confusion_matrix
accuracy_score(y_test, y_pred)

0.464750378214826

In [45]:
confusion_matrix(y_test, y_pred)

array([[ 710, 1311],
       [ 458,  826]])

In [46]:
f1_score(y_test, y_pred)

0.4828997369190295

##### Model for Advisement

In [47]:
y = data['Advisement']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

dtc_advisement = DecisionTreeClassifier()
dtc_advisement.fit(X_train, y_train)

DecisionTreeClassifier()

In [48]:
y_pred = dtc_advisement.predict(X_test)
from sklearn.metrics import accuracy_score, confusion_matrix
accuracy_score(y_test, y_pred)

0.9125567322239032

In [49]:
f1_score(y_test, y_pred)

0.033444816053511704

In [50]:
confusion_matrix(y_test, y_pred)

array([[3011,  169],
       [ 120,    5]])